### ISSUE TITLE
Can't connect socket

### ISSUE THREAD

**Issue by asiermusa** [msonowal/vue-echo#2]
Hi,

I really appreciate this awesome plugin but I couldn't connect to Laravel. Apparently the websocket connection is ok but when I dispatch events from the server I never can catch them in my client. I am working in a separate VUE-CLI SPA app.

I attached some images if you know why the socket is always disconnected

<img width="727" alt="Captura de pantalla 2021-03-05 a las 14 47 27" src="https://user-images.githubusercontent.com/32843723/110124637-9dd45d80-7dc2-11eb-9da9-e6b52f78831b.png">

<img width="713" alt="Captura de pantalla 2021-03-05 a las 14 47 52" src="https://user-images.githubusercontent.com/32843723/110124643-a0cf4e00-7dc2-11eb-80f6-f2dd6fd39e85.png">

.

Thanks!

**Comment by asiermusa** [comment]
Finally I solved the problem downgrading socket.io-client version from 3.*.* to 2.3.1.

**Comment by msonowal** [comment]
great
