### ISSUE TITLE
Version outdated https://www.npmjs.com/package/vue-echo-laravel

### ISSUE THREAD

**Issue by dhcmega** [msonowal/vue-echo#4]
Hi
npm shows last version as 0.0.6, not 0.1.0

https://www.npmjs.com/package/vue-echo-laravel

How can this be fixed?
Thanks!

dhcmega

**Comment by adideas** [comment]
Hi
1) the developer has no time
2) the developer has stopped supporting the repository

Anyway, thanks to him. The library is very good!!

in package.json set version ^1.0! it works!!!!

**Comment by msonowal** [comment]
@adideas  I have not stopped supporting the repository but I missed the notification from github

**Comment by msonowal** [comment]
@dhcmega  @adideas published the latest release
